# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be4b811613dd422699930bb9464588487829e1c276f75c97a44cdc75912008fa22665ec40af6cdaf8be2c97e97f3a5a6d55906ae5c3868fa235adece21694264

test:
  secret_key_base: 6a2bc6295f43c57127fa00063105810c8a80d444e246a31e5bed7470e2cad84520dbd56a4505c4cc4436666aa32f7134f8749a45493ad7277ea7291cf6688ab3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
